version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Lumeza270712"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - net

  checkmarx:
    image: checkmarx/cx-flow
    container_name: checkmarx
    environment:
      - DB_SERVER=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASS=Lumeza270712
      - DB_NAME=CheckmarxDB
      - ACCEPT_EULA=Y
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    volumes:
      - checkmarx-data:/var/opt/checkmarx
    networks:
      - net

networks:
  net:

volumes:
  sqlserver-data:
    external: false
  checkmarx-data:
    external: false
